### ISSUE TITLE
Sentry.Xamarin does not work on .Net 6.0 iOS

### ISSUE THREAD

**Issue by Dolfik1** [getsentry/sentry-xamarin#97]
### Environment

net6.0-ios13.0

### Steps to Reproduce

Invoke `SentryXamarin.Init` in `AppDelegate` constructor.

### Expected Result

The app started without crash and Sentry is initialized successfully.

### Actual Result

The app crashed after start:

```
Unhandled managed exception: Operation is not supported on this platform. 
(System.PlatformNotSupportedException)
   at System.Net.Http.NSUrlSessionHandler.get_SupportsAutomaticDecompression()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
--- End of stack trace from previous location ---
   at System.Net.Http.HttpClientHandler.InvokeNativeHandlerMethod(String name, Object[] parameters)
   at System.Net.Http.HttpClientHandler.GetSupportsAutomaticDecompression()
   at System.Net.Http.HttpClientHandler.get_SupportsAutomaticDecompression()
   at Sentry.Internal.Http.DefaultSentryHttpClientFactory.Create(SentryOptions options)
   at Sentry.Internal.SdkComposer.CreateTransport()
   at Sentry.Internal.SdkComposer.CreateBackgroundWorker()
   at Sentry.SentryClient..ctor(SentryOptions options, IBackgroundWorker worker)
   at Sentry.SentryClient..ctor(SentryOptions options)
   at Sentry.Internal.Hub..ctor(SentryOpti<…>
```

**Comment by lucas-zimerman** [comment]
We are not going to support .NET 6 on this Package.
Instead, we will bring support for it on the main package: https://github.com/getsentry/sentry-dotnet/issues/1282

**Comment by bruno-garcia** [comment]
Closing because we don't expect to support .NET 6 with this package. The goal is to add support in the core .NET SDK
